# Generated by Django 4.2.2 on 2023-10-20 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-last_updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-last_updated', '-created']},
        ),
        migrations.AddField(
            model_name='blogs',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
