# Generated by Django 4.2.2 on 2023-10-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_blogs_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
