# Generated by Django 4.2.2 on 2023-10-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_blogs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(to='apps.tag'),
        ),
    ]
