# Generated by Django 4.2.2 on 2023-10-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_mailnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogview',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(blank=True, to='apps.tag'),
        ),
    ]
