# Generated by Django 4.2.2 on 2023-10-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_blogview_view_count_alter_blogs_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogview',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogview',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='blogview',
            name='user',
        ),
    ]
